apiVersion: v2
description: EcoVadis Helm chart for K8s Cron Job
name: charts-cron-multijob
type: application
version: 1.0.0
dependencies:
- name: charts-core
  version: 2.4.2
  repository: "https://ecovadiscode.github.io/charts/"