apiVersion: v2
description: EcoVadis Helm chart for K8s Event driven Deployment
name: charts-event-worker
type: application
version: 1.2.0
dependencies:
- name: charts-core
  version: 2.4.2
  repository: "https://ecovadiscode.github.io/charts/"