apiVersion: v2
description: EcoVadis Helm chart for .Net Core app
name: charts-dotnet-core
type: application
version: 4.4.1
dependencies:
- name: charts-core
  version: 2.4.2
  repository: "https://ecovadiscode.github.io/charts/"