apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ado-agent-cleaner-role
  namespace: "{{ .Release.Namespace }}"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ado-agent-cleaner-binding
  namespace: "{{ .Release.Namespace }}"
subjects:
  - kind: ServiceAccount
    name: "svc-acc-{{ .Values.podName }}"
roleRef:
  kind: Role
  name: ado-agent-cleaner-role
  apiGroup: rbac.authorization.k8s.io