apiVersion: v2
name: charts-app-reverse-proxy
description: EcoVadis Helm chart for application exposed with nginx reverse proxy
type: application
version: 3.1.0
appVersion: 1.16.0
dependencies:
- name: charts-core
  version: 2.6.0
  repository: "https://ecovadiscode.github.io/charts/"
